// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOJj6lCH_YC_oKvTgBpNu3sd_uptpgeoY',
    appId: '1:424111096561:web:170d980e3d762fa5ae1f50',
    messagingSenderId: '424111096561',
    projectId: 'notfpush-c919d',
    authDomain: 'notfpush-c919d.firebaseapp.com',
    storageBucket: 'notfpush-c919d.appspot.com',
    measurementId: 'G-HRDS8LSJRF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa_0myQ1f76Sn_J5ZDKxP9t9YUqhfhPOU',
    appId: '1:424111096561:android:beb0b94b4d77a494ae1f50',
    messagingSenderId: '424111096561',
    projectId: 'notfpush-c919d',
    storageBucket: 'notfpush-c919d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxAGIG072zd-zOsWHnRfCDCzSQxqeQmA4',
    appId: '1:424111096561:ios:8b4294a25b8c9e62ae1f50',
    messagingSenderId: '424111096561',
    projectId: 'notfpush-c919d',
    storageBucket: 'notfpush-c919d.appspot.com',
    iosBundleId: 'com.example.notfpush',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxAGIG072zd-zOsWHnRfCDCzSQxqeQmA4',
    appId: '1:424111096561:ios:0c13c7e5faec919dae1f50',
    messagingSenderId: '424111096561',
    projectId: 'notfpush-c919d',
    storageBucket: 'notfpush-c919d.appspot.com',
    iosBundleId: 'com.example.notfpush.RunnerTests',
  );
}
